# model
model_name_or_path: meta-llama/Meta-Llama-3-8B
adapter_name_or_path: saves/llama3-8b/lora/sft

# method
finetuning_type: lora

# dataset
task: cmmlu
split: test
template: fewshot
lang: zh
n_shot: 5

# output
save_dir: saves/llama3-8b/lora/chinese-eval

# eval
batch_size: 4
